apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devlink
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: devlink.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devlink-web
                port:
                  number: 80
